services:
    hd-homey:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: ghcr.io/shaunburdick/hd-homey
        ports:
            - "3003:3000"
        volumes:
            - database:/data/db
        environment:
            - HD_HOMEY_DB_PATH=/data/db

volumes:
    database:
