services:
    hd-homey:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: ghcr.io/shaunburdick/hd-homey
        ports:
            - "3000:3000"
        volumes:
            - data:/app/data
        environment:
            - NODE_ENV=production
            - AUTH_TRUST_HOST=true
            - AUTH_SECRET=${AUTH_SECRET:-please-change-this-secret-in-production}
            - HD_HOMEY_DB_PATH=${HD_HOMEY_DB_PATH:-./data/db/hd_homey.db}

volumes:
    data:
