package com.hdhomey.app.di

import android.content.Context
import androidx.annotation.OptIn
import androidx.media3.common.util.UnstableApi
import androidx.media3.database.StandaloneDatabaseProvider
import androidx.media3.datasource.DefaultHttpDataSource
import androidx.media3.datasource.cache.Cache
import androidx.media3.datasource.cache.CacheDataSource
import androidx.media3.datasource.cache.LeastRecentlyUsedCacheEvictor
import androidx.media3.datasource.cache.SimpleCache
import androidx.media3.exoplayer.ExoPlayer
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.android.qualifiers.ApplicationContext
import dagger.hilt.components.SingletonComponent
import java.io.File
import javax.inject.Singleton

/**
 * Hilt DI module providing singleton media playback dependencies.
 *
 * Installed in [SingletonComponent] so the [ExoPlayer] and [Cache] instances are shared across
 * the entire application lifetime. A single player is appropriate here because HD Homey streams
 * one channel at a time; sharing the instance avoids the cost of creating and releasing the
 * player on every navigation event.
 *
 * **Important**: Consumers are responsible for calling [ExoPlayer.release] and [Cache.release]
 * when the application is destroyed (e.g., in [android.app.Application.onTerminate] or a
 * lifecycle-aware wrapper).
 */
@Module
@InstallIn(SingletonComponent::class)
object MediaModule {

    /** Maximum on-disk cache size for ExoPlayer buffering: 50 MB. */
    private const val CACHE_MAX_BYTES = 50L * 1024L * 1024L

    /**
     * Provides the application-scoped [ExoPlayer] instance.
     *
     * Uses [ApplicationContext] rather than an Activity context to prevent memory leaks —
     * the player outlives any individual screen.
     *
     * @param context Application context injected by Hilt
     * @return A fully initialised [ExoPlayer] ready for playback
     */
    @Provides
    @Singleton
    fun provideExoPlayer(@ApplicationContext context: Context): ExoPlayer {
        return ExoPlayer.Builder(context).build()
    }

    /**
     * Provides the application-scoped [Cache] used by ExoPlayer to buffer live HLS streams.
     *
     * Uses [LeastRecentlyUsedCacheEvictor] with a 50 MB cap so the cache never grows
     * unbounded on constrained devices. The cache directory is isolated under the app's
     * private [Context.getCacheDir] so it is cleared automatically when the user clears
     * app data.
     *
     * **Note**: [SimpleCache], [LeastRecentlyUsedCacheEvictor], and [StandaloneDatabaseProvider]
     * are annotated with `@UnstableApi` by Media3. The API contract is stable in practice (used
     * in production apps worldwide), but Google reserves the right to change it between minor
     * releases.
     *
     * @param context Application context injected by Hilt
     * @return A [SimpleCache] instance bounded to 50 MB
     */
    @OptIn(UnstableApi::class)
    @Provides
    @Singleton
    fun provideCache(@ApplicationContext context: Context): Cache {
        val cacheDir = File(context.cacheDir, "exoplayer-cache")
        val evictor = LeastRecentlyUsedCacheEvictor(CACHE_MAX_BYTES)
        val databaseProvider = StandaloneDatabaseProvider(context)
        return SimpleCache(cacheDir, evictor, databaseProvider)
    }

    /**
     * Provides the [CacheDataSource.Factory] that wraps ExoPlayer's cache layer over a plain
     * HTTP upstream.
     *
     * Reads from the [Cache] first; only fetches from [DefaultHttpDataSource] on a cache miss.
     * [CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR] ensures that a corrupt or incomplete cache
     * entry falls back to the network rather than surfacing a read error to the player.
     *
     * **Why [DefaultHttpDataSource] instead of the app's OkHttp client?**
     * The HLS playlist URL already contains an HMAC token generated by
     * [com.hdhomey.app.domain.usecase.GenerateStreamUrlUseCase]. The token authenticates the
     * request without requiring an `Authorization` header, so the auth interceptor is not
     * needed here. Using [DefaultHttpDataSource] avoids pulling the full OkHttp stack into
     * the media pipeline.
     *
     * @param cache Singleton [Cache] instance provided by [provideCache]
     * @return A configured [CacheDataSource.Factory] for cache-first HLS fetching
     */
    @OptIn(UnstableApi::class)
    @Provides
    @Singleton
    fun provideCacheDataSourceFactory(cache: Cache): CacheDataSource.Factory {
        return CacheDataSource.Factory()
            .setCache(cache)
            .setUpstreamDataSourceFactory(DefaultHttpDataSource.Factory())
            .setFlags(CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)
    }
}
