import { relations, sql } from 'drizzle-orm';
import { sqliteTable, text, integer, index, unique } from 'drizzle-orm/sqlite-core';

// ===================================
// Better-Auth Tables (GENERATED - DO NOT MODIFY COLUMN NAMES)
// ===================================

/**
 * Better-Auth user table
 * IMPORTANT: Column names use snake_case as generated by Better-Auth CLI
 * Drizzle property names use camelCase for TypeScript, but DB columns are snake_case
 */
export const user = sqliteTable('user', {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    name: text('name').notNull(),
    email: text('email').notNull().unique(),
    emailVerified: integer('email_verified', { mode: 'boolean' })
        .default(false)
        .notNull(),
    image: text('image'),
    createdAt: integer('created_at', { mode: 'timestamp_ms' })
        .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
        .notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
        .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
        .$onUpdate(() => /* @__PURE__ */ new Date())
        .notNull(),
    // Username plugin fields
    username: text('username').unique(),
    displayUsername: text('display_username'),
    // HD Homey custom fields
    role: text('role').default('viewer').notNull(),
    isActive: integer('is_active', { mode: 'boolean' }).default(true).notNull(),
    deletedAt: integer('deleted_at', { mode: 'timestamp_ms' }),
});

export type User = typeof user.$inferSelect;

/**
 * Better-Auth session table
 * Required for database-backed sessions (we're using JWT but keeping for future)
 */
export const session = sqliteTable(
    'session',
    {
        id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
        expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
        token: text('token').notNull().unique(),
        createdAt: integer('created_at', { mode: 'timestamp_ms' })
            .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
            .notNull(),
        updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
            .$onUpdate(() => /* @__PURE__ */ new Date())
            .notNull(),
        ipAddress: text('ip_address'),
        userAgent: text('user_agent'),
        userId: text('user_id')
            .notNull()
            .references(() => user.id, { onDelete: 'cascade' }),
    },
    (table) => [index('session_userId_idx').on(table.userId)],
);

/**
 * Better-Auth account table
 * Stores OAuth tokens and credential passwords
 */
export const account = sqliteTable(
    'account',
    {
        id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
        accountId: text('account_id').notNull(),
        providerId: text('provider_id').notNull(),
        userId: text('user_id')
            .notNull()
            .references(() => user.id, { onDelete: 'cascade' }),
        accessToken: text('access_token'),
        refreshToken: text('refresh_token'),
        idToken: text('id_token'),
        accessTokenExpiresAt: integer('access_token_expires_at', {
            mode: 'timestamp_ms',
        }),
        refreshTokenExpiresAt: integer('refresh_token_expires_at', {
            mode: 'timestamp_ms',
        }),
        scope: text('scope'),
        password: text('password'),
        createdAt: integer('created_at', { mode: 'timestamp_ms' })
            .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
            .notNull(),
        updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
            .$onUpdate(() => /* @__PURE__ */ new Date())
            .notNull(),
    },
    (table) => [index('account_userId_idx').on(table.userId)],
);

/**
 * Better-Auth verification table
 * For email verification, password reset, etc.
 */
export const verification = sqliteTable(
    'verification',
    {
        id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
        identifier: text('identifier').notNull(),
        value: text('value').notNull(),
        expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
        createdAt: integer('created_at', { mode: 'timestamp_ms' })
            .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
            .notNull(),
        updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
            .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
            .$onUpdate(() => /* @__PURE__ */ new Date())
            .notNull(),
    },
    (table) => [index('verification_identifier_idx').on(table.identifier)],
);

// Better-Auth Relations
export const userRelations = relations(user, ({ many }) => ({
    sessions: many(session),
    accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
    user: one(user, {
        fields: [session.userId],
        references: [user.id],
    }),
}));

export const accountRelations = relations(account, ({ one }) => ({
    user: one(user, {
        fields: [account.userId],
        references: [user.id],
    }),
}));

// ===================================
// HD Homey Tables (UNCHANGED)
// ===================================

export const tuners = sqliteTable('tuners', {
    id: integer('id', { mode: 'number' }).primaryKey({ autoIncrement: true }),
    name: text('name', { length: 255 }).notNull(),
    path: text('path').notNull(),
    last_scanned: integer('last_scanned', { mode: 'timestamp' }),
    is_active: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
    modified_at: integer('modified_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
    deleted_at: integer('deleted_at', { mode: 'timestamp' })
});

export type Tuner = typeof tuners.$inferSelect;

export const channels = sqliteTable('channels', {
    id: integer('id', { mode: 'number' }).primaryKey({ autoIncrement: true }),
    fk_tuner: integer('fk_tuner', { mode: 'number' }).notNull().references(() => tuners.id),
    guideNumber: text('guideNumber').notNull(),
    guideName: text('guideName').notNull(),
    videoCodec: text('videoCodec').notNull(),
    audioCodec: text('audioCodec').notNull(),
    hd: integer('hd', { mode: 'number' }).notNull(),
    url: text('url').notNull(),
    is_active: integer('is_active', { mode: 'boolean' }).notNull().default(true),
    created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
    modified_at: integer('modified_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
    deleted_at: integer('deleted_at', { mode: 'timestamp' })
}, (table) => [
    unique('tuner_guideNumber').on(table.fk_tuner, table.guideNumber),
]);

export type Channel = typeof channels.$inferSelect;

export const tunerRelations = relations(tuners, ({ many }) => ({
    channels: many(channels)
}));

export const channelRelations = relations(channels, ({ one }) => ({
    tuners: one(tuners, {
        fields: [channels.fk_tuner],
        references: [tuners.id]
    })
}));

// Settings
export const settings = sqliteTable('settings', {
    key: text('key', { length: 255 }).primaryKey(),
    value: text('value').notNull(),
    created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
    modified_at: integer('modified_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`)
});

export type Setting = typeof settings.$inferSelect;

// ===================================
// Invitations Table (SPEC-010)
// ===================================

/**
 * Invitations table for user invitation system
 * Allows admins to generate secure one-time-use invitation links
 */
export const invitations = sqliteTable(
    'invitations',
    {
        id: integer('id', { mode: 'number' }).primaryKey({ autoIncrement: true }),
        token: text('token', { length: 64 }).notNull().unique(), // URL-safe base64 encoded (32 bytes)
        role: text('role', { length: 20 }).notNull(), // 'admin' or 'viewer'
        note: text('note', { length: 200 }), // Optional admin label
        createdBy: text('created_by')
            .notNull()
            .references(() => user.id, { onDelete: 'restrict' }),
        createdAt: integer('created_at', { mode: 'timestamp_ms' })
            .notNull()
            .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
        expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
        usedAt: integer('used_at', { mode: 'timestamp_ms' }),
        usedBy: text('used_by').references(() => user.id, { onDelete: 'restrict' }),
        revokedAt: integer('revoked_at', { mode: 'timestamp_ms' }),
        revokedBy: text('revoked_by').references(() => user.id, { onDelete: 'restrict' }),
    },
    (table) => [
        index('idx_invitations_token').on(table.token),
        index('idx_invitations_created_by').on(table.createdBy),
        index('idx_invitations_status').on(table.usedAt, table.expiresAt, table.revokedAt),
    ]
);

export type Invitation = typeof invitations.$inferSelect;

// Invitation Relations
export const invitationRelations = relations(invitations, ({ one }) => ({
    creator: one(user, {
        fields: [invitations.createdBy],
        references: [user.id],
        relationName: 'invitationCreator',
    }),
    redeemer: one(user, {
        fields: [invitations.usedBy],
        references: [user.id],
        relationName: 'invitationRedeemer',
    }),
    revoker: one(user, {
        fields: [invitations.revokedBy],
        references: [user.id],
        relationName: 'invitationRevoker',
    }),
}));

// ===================================
// User Channel Preferences Table (SPEC-012)
// ===================================

/**
 * User channel preferences table for favorites and hidden channels
 * Stores per-user preferences for organizing channels
 */
export const userChannelPreferences = sqliteTable(
    'user_channel_preferences',
    {
        id: integer('id', { mode: 'number' }).primaryKey({ autoIncrement: true }),
        userId: text('user_id')
            .notNull()
            .references(() => user.id, { onDelete: 'cascade' }),
        channelId: integer('channel_id', { mode: 'number' })
            .notNull()
            .references(() => channels.id, { onDelete: 'cascade' }),
        isFavorite: integer('is_favorite', { mode: 'boolean' }).notNull().default(false),
        isHidden: integer('is_hidden', { mode: 'boolean' }).notNull().default(false),
        updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
            .notNull()
            .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`),
    },
    (table) => ({
        userChannelUnique: unique(
            'user_channel_preferences_user_id_channel_id_unique'
        ).on(table.userId, table.channelId),
        userIdx: index('idx_user_channel_prefs_user').on(table.userId),
        userChannelIdx: index('idx_user_channel_prefs_user_channel')
            .on(table.userId, table.channelId),
    })
);

export type UserChannelPreference = typeof userChannelPreferences.$inferSelect;
export type UserChannelPreferenceInsert = typeof userChannelPreferences.$inferInsert;

// User Channel Preferences Relations
export const userChannelPreferenceRelations = relations(userChannelPreferences, ({ one }) => ({
    user: one(user, {
        fields: [userChannelPreferences.userId],
        references: [user.id],
    }),
    channel: one(channels, {
        fields: [userChannelPreferences.channelId],
        references: [channels.id],
    }),
}));

/**
 * Channel with user preference data joined
 * Used by ChannelOrganizer to display channels with their preference state
 * Note: isFavorite and isHidden are booleans because the schema uses mode: 'boolean'
 */
export interface ChannelWithPreference {
    id: number;
    guideNumber: string;
    guideName: string;
    url: string | null;
    hd: number;
    videoCodec: string | null;
    audioCodec: string | null;
    fk_tuner: number;
    isFavorite: boolean | null;
    isHidden: boolean | null;
}
